"""
Concurrent Load Test Script for Autonomous Multi-Agent Pipeline.
Executes 200 total requests across 30 concurrent workers using httpx.AsyncClient
with asyncio.Semaphore(30) and asyncio.gather.
Randomly reuses the 10 sample queries (specific, ambiguous, and fallback).
Continuously tracks peak docker CPU and memory stats during the test execution window.
"""

import asyncio
import httpx
import random
import time
import subprocess
import json
import statistics
import os

QUERIES = [
    "What is the per diem meal limit for domestic and international business travel?",
    "What consensus mechanism and failover time are used for PostgreSQL high availability?",
    "What service credit is issued if monthly uptime falls below 95%?",
    "What error rate threshold triggers an automated rollback during canary deployments?",
    "What is the Time-to-Live for dynamic database credentials generated by HashiCorp Vault?",
    "Can I get my money back if I cancel my subscription early?",
    "How is damaged or defective hardware replaced?",
    "How long are security audit logs retained before permanent deletion?",
    "How many weeks of paid leave are employees entitled to for family or sabbatical?",
    "What is your policy on cryptocurrency payments?"
]

DOCKER_BIN = "/Users/rithwikdevireddy/.docker/bin/docker"

import threading

class DockerStatsMonitor:
    def __init__(self, container_name="agentic_api"):
        self.container_name = container_name
        self.running = False
        self.peak_cpu = 0.0
        self.peak_mem_mib = 0.0
        self.peak_mem_str = "0MiB"
        self.peak_mem_perc = 0.0
        self.samples = []
        self._thread = None
        # baseline read
        self._sample_once()

    def _sample_once(self):
        try:
            res = subprocess.run(
                [DOCKER_BIN, "stats", self.container_name, "--no-stream",
                 "--format", "{{.CPUPerc}}\t{{.MemUsage}}\t{{.MemPerc}}"],
                capture_output=True, text=True, timeout=3.0
            )
            line = res.stdout.strip()
            parts = line.split("\t")
            if len(parts) >= 3:
                cpu_str = parts[0].replace("%", "").strip()
                mem_str = parts[1].split("/")[0].strip()
                perc_str = parts[2].replace("%", "").strip()

                cpu_val = float(cpu_str)
                perc_val = float(perc_str)
                if "GiB" in mem_str:
                    mem_mib = float(mem_str.replace("GiB", "").strip()) * 1024
                elif "MiB" in mem_str:
                    mem_mib = float(mem_str.replace("MiB", "").strip())
                elif "kB" in mem_str:
                    mem_mib = float(mem_str.replace("kB", "").strip()) / 1024
                else:
                    mem_mib = 0.0

                self.peak_cpu = max(self.peak_cpu, cpu_val)
                if mem_mib >= self.peak_mem_mib:
                    self.peak_mem_mib = mem_mib
                    self.peak_mem_str = mem_str
                self.peak_mem_perc = max(self.peak_mem_perc, perc_val)
                self.samples.append((time.time(), cpu_val, mem_mib, perc_val))
        except Exception:
            pass

    def _run(self):
        while self.running:
            self._sample_once()
            time.sleep(0.1)

    def start(self):
        self.running = True
        self._thread = threading.Thread(target=self._run, daemon=True)
        self._thread.start()

    def stop(self):
        self.running = False
        if self._thread:
            self._thread.join(timeout=1.0)

async def worker_task(client, sem, req_id, query, results):
    payload = {
        "query": query,
        "top_k": 3,
        "enable_reranking": True,
        "enable_verification": True
    }
    async with sem:
        t0 = time.perf_counter()
        try:
            resp = await client.post("/api/v1/query", json=payload, timeout=60.0)
            elapsed_ms = (time.perf_counter() - t0) * 1000.0
            if resp.status_code == 200:
                body = resp.json()
                results.append({
                    "req_id": req_id,
                    "query": query,
                    "status_code": 200,
                    "elapsed_ms": round(elapsed_ms, 2),
                    "cached": body.get("cached", False),
                    "execution_time_ms": body.get("execution_time_ms", 0.0),
                    "error": None
                })
            else:
                results.append({
                    "req_id": req_id,
                    "query": query,
                    "status_code": resp.status_code,
                    "elapsed_ms": round(elapsed_ms, 2),
                    "cached": False,
                    "execution_time_ms": None,
                    "error": f"HTTP {resp.status_code}: {resp.text[:120]}"
                })
        except Exception as e:
            elapsed_ms = (time.perf_counter() - t0) * 1000.0
            results.append({
                "req_id": req_id,
                "query": query,
                "status_code": 0,
                "elapsed_ms": round(elapsed_ms, 2),
                "cached": False,
                "execution_time_ms": None,
                "error": f"{type(e).__name__}: {str(e)}"
            })

def calc_percentiles(values):
    if not values:
        return {"count": 0, "min": 0, "p50": 0, "p90": 0, "p95": 0, "p99": 0, "max": 0, "mean": 0}
    vals = sorted(values)
    n = len(vals)
    return {
        "count": n,
        "min": round(vals[0], 2),
        "p50": round(statistics.median(vals), 2),
        "p90": round(vals[int((n - 1) * 0.90)], 2),
        "p95": round(vals[int((n - 1) * 0.95)], 2),
        "p99": round(vals[int((n - 1) * 0.99)], 2),
        "max": round(vals[-1], 2),
        "mean": round(statistics.mean(vals), 2)
    }

async def run_load_test():
    total_requests = 200
    concurrency = 30
    base_url = "http://localhost:8000"

    print("=" * 80)
    print(f"Starting Load Test: {total_requests} requests across {concurrency} concurrent workers")
    print(f"Target: {base_url}/api/v1/query")
    print(f"Corpus size: 112 documents in pgvector and in-memory index")
    print("=" * 80)

    # Randomly select queries for the 200 requests
    random.seed(42)  # reproducible random distribution
    selected_queries = [random.choice(QUERIES) for _ in range(total_requests)]

    # Start docker monitor thread
    monitor = DockerStatsMonitor("agentic_api")
    monitor.start()

    # Get container initial status
    res_before = subprocess.check_output(
        [DOCKER_BIN, "stats", "agentic_api", "--no-stream", "--format", "{{.CPUPerc}}\t{{.MemUsage}}\t{{.MemPerc}}"]
    ).decode().strip()
    print(f"Initial Docker Stats: {res_before}")

    sem = asyncio.Semaphore(concurrency)
    results = []

    # Configure httpx client with connection pooling
    limits = httpx.Limits(max_connections=concurrency + 10, max_keepalive_connections=concurrency)
    async with httpx.AsyncClient(base_url=base_url, limits=limits, timeout=60.0) as client:
        start_time = time.perf_counter()
        tasks = [
            worker_task(client, sem, i, selected_queries[i], results)
            for i in range(total_requests)
        ]
        await asyncio.gather(*tasks)
        total_duration = time.perf_counter() - start_time

    # Stop monitor thread
    monitor.stop()

    res_after = subprocess.check_output(
        [DOCKER_BIN, "stats", "agentic_api", "--no-stream", "--format", "{{.CPUPerc}}\t{{.MemUsage}}\t{{.MemPerc}}"]
    ).decode().strip()

    # Separate into groups
    successes = [r for r in results if r["status_code"] == 200]
    failures = [r for r in results if r["status_code"] != 200]
    cached_hits = [r for r in successes if r["cached"]]
    cached_misses = [r for r in successes if not r["cached"]]

    # Per-request roundtrip latencies
    all_latencies = [r["elapsed_ms"] for r in results]
    cold_latencies = [r["elapsed_ms"] for r in cached_misses]
    hit_latencies = [r["elapsed_ms"] for r in cached_hits]

    # Server-side execution times
    cold_exec_times = [r["execution_time_ms"] for r in cached_misses if r["execution_time_ms"] is not None]
    hit_exec_times = [r["execution_time_ms"] for r in cached_hits if r["execution_time_ms"] is not None]

    stats_all = calc_percentiles(all_latencies)
    stats_cold = calc_percentiles(cold_latencies)
    stats_hit = calc_percentiles(hit_latencies)
    stats_cold_exec = calc_percentiles(cold_exec_times)
    stats_hit_exec = calc_percentiles(hit_exec_times)

    print("\n" + "=" * 80)
    print("LOAD TEST EXECUTION RESULTS (SEPARATED DISTRIBUTIONS)")
    print("=" * 80)
    print(f"Total Requests:       {len(results)}")
    print(f"Successful (HTTP 200): {len(successes)} ({len(successes)/len(results)*100:.1f}%)")
    print(f"Failed:               {len(failures)} ({len(failures)/len(results)*100:.1f}%)")
    print(f"Cache Hits:           {len(cached_hits)} ({len(cached_hits)/len(successes)*100:.1f}%)")
    print(f"Cache Misses (Cold):  {len(cached_misses)} ({len(cached_misses)/len(successes)*100:.1f}%)")
    print(f"Total Test Duration:  {total_duration:.2f} seconds")
    print(f"Overall Throughput:   {len(results)/total_duration:.2f} requests/sec")
    print("-" * 80)

    print("GROUP 1: COLD / CACHE-MISS REQUESTS ONLY (Full Pipeline: BM25 + pgvector + Rerank + Verifier)")
    print(f"  Count:  {stats_cold['count']} requests")
    print(f"  Per-Request HTTP Latency (ms):")
    print(f"    Min:  {stats_cold['min']} ms  |  p50:  {stats_cold['p50']} ms  |  Mean: {stats_cold['mean']} ms")
    print(f"    p90:  {stats_cold['p90']} ms  |  p95:  {stats_cold['p95']} ms  |  p99:  {stats_cold['p99']} ms  |  Max: {stats_cold['max']} ms")
    print(f"  Server-Reported execution_time_ms:")
    print(f"    Min:  {stats_cold_exec['min']} ms  |  p50:  {stats_cold_exec['p50']} ms  |  p95:  {stats_cold_exec['p95']} ms  |  Max: {stats_cold_exec['max']} ms")
    print("-" * 80)

    print("GROUP 2: WARM / CACHE-HIT REQUESTS ONLY (Redis In-Memory Lookup)")
    print(f"  Count:  {stats_hit['count']} requests")
    print(f"  Per-Request HTTP Latency (ms):")
    print(f"    Min:  {stats_hit['min']} ms  |  p50:  {stats_hit['p50']} ms  |  Mean: {stats_hit['mean']} ms")
    print(f"    p90:  {stats_hit['p90']} ms  |  p95:  {stats_hit['p95']} ms  |  p99:  {stats_hit['p99']} ms  |  Max: {stats_hit['max']} ms")
    print(f"  Server-Reported execution_time_ms:")
    print(f"    Min:  {stats_hit_exec['min']} ms  |  p50:  {stats_hit_exec['p50']} ms  |  p95:  {stats_hit_exec['p95']} ms  |  Max: {stats_hit_exec['max']} ms")
    print("-" * 80)

    print(f"Docker Stats (agentic_api):")
    print(f"  Before Test:  {res_before}")
    print(f"  Peak CPU:     {monitor.peak_cpu:.2f}%")
    print(f"  Peak Memory:  {monitor.peak_mem_str} ({monitor.peak_mem_perc:.2f}%)")
    print(f"  After Test:   {res_after}")
    print("=" * 80)

    if failures:
        print("\nFAILURE DETAILS:")
        for f in failures:
            print(f"  Req #{f['req_id']}: {f['error']}")

    # Save results to json
    report = {
        "total_requests": len(results),
        "concurrency": concurrency,
        "success_count": len(successes),
        "failure_count": len(failures),
        "success_rate_percent": round(len(successes)/len(results)*100, 2),
        "duration_seconds": round(total_duration, 2),
        "throughput_rps": round(len(results)/total_duration, 2),
        "group_1_cold_miss": {
            "stats_http_latency_ms": stats_cold,
            "stats_server_execution_time_ms": stats_cold_exec,
        },
        "group_2_warm_hit": {
            "stats_http_latency_ms": stats_hit,
            "stats_server_execution_time_ms": stats_hit_exec,
        },
        "docker_stats": {
            "initial": res_before,
            "peak_cpu_percent": monitor.peak_cpu,
            "peak_memory_str": monitor.peak_mem_str,
            "peak_memory_percent": monitor.peak_mem_perc,
            "final": res_after
        },
        "requests": results
    }
    with open("scripts/load_test_results.json", "w") as f:
        json.dump(report, f, indent=2)
    print("\nDetailed per-request results saved to scripts/load_test_results.json")

if __name__ == "__main__":
    asyncio.run(run_load_test())
