"""
Executes 10 sample queries (specific, ambiguous, and out-of-domain) against the expanded corpus.
Reports retrieval precision, top chunk matches, executive summaries, and verifier verdicts.
"""

import json
import time
import urllib.request
import urllib.error

QUERIES = [
    {
        "id": 1,
        "type": "Specific (HR / Travel)",
        "query": "What is the per diem meal limit for domestic and international business travel?",
        "expected_domain": "Corporate Travel and Expense Reimbursement Policy 2026"
    },
    {
        "id": 2,
        "type": "Specific (Database HA)",
        "query": "What consensus mechanism and failover time are used for PostgreSQL high availability?",
        "expected_domain": "PostgreSQL Streaming Replication, Patroni Failover, and Connection Pooling"
    },
    {
        "id": 3,
        "type": "Specific (Enterprise SLA)",
        "query": "What service credit is issued if monthly uptime falls below 95%?",
        "expected_domain": "Enterprise Cloud Infrastructure Service Level Agreement (SLA)"
    },
    {
        "id": 4,
        "type": "Specific (DevOps / Canary)",
        "query": "What error rate threshold triggers an automated rollback during canary deployments?",
        "expected_domain": "Canary Deployments, Progressive Delivery, and Automated Rollbacks"
    },
    {
        "id": 5,
        "type": "Specific (Security / Secrets)",
        "query": "What is the Time-to-Live for dynamic database credentials generated by HashiCorp Vault?",
        "expected_domain": "Secrets Management, HashiCorp Vault, and Dynamic Credential Rotation"
    },
    {
        "id": 6,
        "type": "Ambiguous (Refunds & Cancellations)",
        "query": "Can I get my money back if I cancel my subscription early?",
        "expected_domain": "Subscription Cancellation or Refund Policy"
    },
    {
        "id": 7,
        "type": "Ambiguous (Hardware Replacement)",
        "query": "How is damaged or defective hardware replaced?",
        "expected_domain": "Hardware Appliance Replacement or Asset Offboarding"
    },
    {
        "id": 8,
        "type": "Ambiguous (Audit Log Retention)",
        "query": "How long are security audit logs retained before permanent deletion?",
        "expected_domain": "Audit Logging, Data Retention, or Log Aggregation"
    },
    {
        "id": 9,
        "type": "Ambiguous (Extended Leaves)",
        "query": "How many weeks of paid leave are employees entitled to for family or sabbatical?",
        "expected_domain": "Parental Leave or Sabbatical Program"
    },
    {
        "id": 10,
        "type": "Out-of-Domain (No Information Fallback)",
        "query": "What is your policy and discount on cryptocurrency payments?",
        "expected_domain": "None (Honest admission of no information)"
    }
]

def main():
    endpoint = "http://localhost:8000/api/v1/query"
    print("=" * 80)
    print("Evaluating Retrieval Precision on 100+ Document Expanded Corpus")
    print("=" * 80)

    results = []

    for q in QUERIES:
        payload = json.dumps({
            "query": q["query"],
            "top_k": 3,
            "enable_reranking": True,
            "enable_verification": True
        }).encode("utf-8")

        req = urllib.request.Request(
            endpoint,
            data=payload,
            headers={"Content-Type": "application/json"}
        )

        t0 = time.perf_counter()
        try:
            with urllib.request.urlopen(req, timeout=45) as resp:
                data = json.loads(resp.read().decode("utf-8"))
                elapsed = (time.perf_counter() - t0) * 1000

                retrieved = data.get("retrieved_chunks", [])
                analysis = data.get("analysis", {})
                verification = data.get("verification", {})

                top_chunk_info = []
                for c in retrieved:
                    title = c.get("metadata", {}).get("title") or "Unknown Title"
                    content_snip = c.get("content", "")[:90].replace("\n", " ")
                    score = c.get("rerank_score", c.get("score", 0.0))
                    top_chunk_info.append({"title": title, "score": score, "snippet": content_snip})

                result = {
                    "id": q["id"],
                    "type": q["type"],
                    "query": q["query"],
                    "expected_domain": q["expected_domain"],
                    "elapsed_ms": round(elapsed, 1),
                    "execution_time_ms": data.get("execution_time_ms"),
                    "cached": data.get("cached"),
                    "chunks_retrieved_count": len(retrieved),
                    "top_chunks": top_chunk_info,
                    "executive_summary": analysis.get("executive_summary"),
                    "key_metrics": analysis.get("key_metrics", []),
                    "confidence_score": analysis.get("confidence_score"),
                    "is_faithful": verification.get("is_faithful"),
                    "hallucination_score": verification.get("hallucination_score"),
                    "unsupported_claims": verification.get("unsupported_claims", [])
                }
                results.append(result)

                print(f"\n--- Query #{q['id']}: [{q['type']}] ---")
                print(f"Query: \"{q['query']}\"")
                print(f"Retrieved: {len(retrieved)} chunk(s) in {elapsed:.1f}ms")
                for idx, tc in enumerate(top_chunk_info, 1):
                    sc = f"{tc['score']:.3f}" if tc['score'] is not None else "N/A"
                    print(f"  [{idx}] {tc['title']} (score: {sc})")
                    print(f"      Snippet: {tc['snippet']}...")
                summary_text = (analysis.get('executive_summary') or "")[:140]
                print(f"Executive Summary: {summary_text}...")
                print(f"Verification: is_faithful={verification.get('is_faithful')}, hallucination_score={verification.get('hallucination_score')}")

        except Exception as e:
            print(f"Query #{q['id']} failed: {e}")

    # Save detailed evaluation report
    with open("scripts/query_evaluation_report.json", "w") as f:
        json.dump(results, f, indent=2)
    print("\n" + "=" * 80)
    print("Full query evaluation report saved to scripts/query_evaluation_report.json")
    print("=" * 80)

if __name__ == "__main__":
    main()
